[2025-04-24T00:00:00.856+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-24T00:00:00.865+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl_dag.load_spotify_csv_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:00.868+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl_dag.load_spotify_csv_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [queued]>
[2025-04-24T00:00:00.868+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-24T00:00:00.873+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): load_spotify_csv_to_snowflake> on 2025-04-23 00:00:00+00:00
[2025-04-24T00:00:00.877+0000] {standard_task_runner.py:72} INFO - Started process 1462 to run task
[2025-04-24T00:00:00.879+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_dag', 'load_spotify_csv_to_snowflake', 'scheduled__2025-04-23T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/spotify_etl_dag.py', '--cfg-path', '/tmp/tmpesv8fper']
[2025-04-24T00:00:00.880+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask load_spotify_csv_to_snowflake
[2025-04-24T00:00:00.903+0000] {task_command.py:467} INFO - Running <TaskInstance: spotify_etl_dag.load_spotify_csv_to_snowflake scheduled__2025-04-23T00:00:00+00:00 [running]> on host fb7f0aec2fef
[2025-04-24T00:00:00.935+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spotify_etl_dag' AIRFLOW_CTX_TASK_ID='load_spotify_csv_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:00:00+00:00'
[2025-04-24T00:00:00.936+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-24T00:00:00.969+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-24T00:00:00.970+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.10.14, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-24T00:00:00.971+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-24T00:00:00.971+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T00:00:01.655+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-24T00:12:48.172+0000] {job.py:229} INFO - Heartbeat recovered after 46.21 seconds
[2025-04-24T00:31:43.487+0000] {job.py:229} INFO - Heartbeat recovered after 122.11 seconds
[2025-04-24T04:05:18.000+0000] {job.py:229} INFO - Heartbeat recovered after 3996.57 seconds
[2025-04-24T04:37:12.245+0000] {job.py:229} INFO - Heartbeat recovered after 1889.04 seconds
[2025-04-24T04:59:20.989+0000] {job.py:229} INFO - Heartbeat recovered after 1212.66 seconds
[2025-04-24T04:59:31.126+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2025-04-24T04:59:31.133+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-24T04:59:31.135+0000] {process_utils.py:132} INFO - Sending 15 to group 1462. PIDs of all processes in the group: [1462]
[2025-04-24T04:59:31.136+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1462
[2025-04-24T04:59:31.137+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-04-24T04:59:31.139+0000] {connection.py:788} INFO - closed
[2025-04-24T04:59:31.268+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-04-24T04:59:31.352+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/load_spotify_to_snowflake.py", line 36, in load_csv_to_snowflake
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 984, in execute
    ret = self._execute_helper(query, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 695, in _execute_helper
    ret = self._connection.cmd_query(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/connection.py", line 1350, in cmd_query
    ret = self.rest.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/network.py", line 491, in request
    return self._post_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/network.py", line 739, in _post_request
    ret = self.fetch(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/network.py", line 854, in fetch
    ret = self._request_exec_wrapper(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/network.py", line 896, in _request_exec_wrapper
    return_object = self._request_exec(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/network.py", line 1059, in _request_exec
    raw_ret = session.request(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/local/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/contrib/pyopenssl.py", line 330, in recv_into
    if not util.wait_for_read(self.socket, self.socket.gettimeout()):
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 145, in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 106, in poll_wait_for_socket
    return bool(_retry_on_intr(do_poll, timeout))
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 43, in _retry_on_intr
    return fn(timeout)
  File "/home/airflow/.local/lib/python3.10/site-packages/snowflake/connector/vendored/urllib3/util/wait.py", line 104, in do_poll
    return poll_obj.poll(t)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3094, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-04-24T04:59:31.367+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_etl_dag, task_id=load_spotify_csv_to_snowflake, run_id=scheduled__2025-04-23T00:00:00+00:00, execution_date=20250423T000000, start_date=20250424T000000, end_date=20250424T045931
[2025-04-24T04:59:31.376+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-24T04:59:31.418+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1462, status='terminated', exitcode=2, started='00:00:00') (1462) terminated with exit code 2
